name: End-to-end test of EasyBuild in different distros
on: [push, pull_request]
jobs:
  build_publish:
    name: End-to-end test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - centos-7.9
          - centos-8.5
          - fedora-36
          - opensuse-15.4
          - rockylinux-8.7
          - ubuntu-20.04
          - ubuntu-22.04
      fail-fast: false
    container:
      image: ghcr.io/easybuilders/${{ matrix.container }}-amd64
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: download and unpack easyblocks and easyconfigs repositories
        run: |
          cd $HOME
          for pkg in easyblocks easyconfigs; do
              curl -OL https://github.com/easybuilders/easybuild-${pkg}/archive/develop.tar.gz
              tar xfz develop.tar.gz
              rm -f develop.tar.gz
          done

      - name: Set up environment
        shell: bash
        run: |
          export PATH=$PWD:$PATH
          export PYTHONPATH=$PWD:$HOME/easybuild-easyblocks-develop:$HOME/easybuild-easyconfigs-develop

          # initialize environment (for Lmod)
          if [ -f /etc/profile.d/modules.sh ]; then
              # for Rocky, CentOS 8, Fedora
              echo ">>> sourcing /etc/profile.d/modules.sh"
              . /etc/profile.d/modules.sh
          else
              echo ">>> sourcing /etc/profile.d/*lmod*.sh"
              . /etc/profile.d/*lmod*.sh
          fi

          # tests are run with root privileges, so we need to tell EasyBuild that's OK...
          export EASYBUILD_ALLOW_USE_AS_ROOT_AND_ACCEPT_CONSEQUENCES=1

          # save full environment to use in subsequent steps,
          # see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
          while read line; do echo "$line" >> $GITHUB_ENV ; done < <(env)

      - name: Run commands to check test environment
        shell: bash
        run: |
          cmds=(
            "whoami"
            "pwd"
            "env | sort"
            "eb --version"
            "eb --show-system-info"
            "eb --check-eb-deps"
            "eb --show-config"
          )
          for cmd in "${cmds[@]}"; do
              echo ">>> $cmd"
              eval "$cmd"
          done

      - name: End-to-end test of installing bzip2 with EasyBuild
        shell: bash
        run: |
          eb bzip2-1.0.8.eb --trace --robot
